### ISSUE TITLE
panic with tracing slice out of bounds

### ISSUE THREAD

**Issue by mzimmerman** [smartystreets/smartystreets-go-sdk#12]
```
panic: runtime error: slice bounds out of range [:938] with capacity 873

goroutine 47471 [running]:
bytes.(*Buffer).grow(0xcef79db5f0, 0xd, 0x122fc20)
        /usr/local/go/src/bytes/buffer.go:148 +0x2b8
bytes.(*Buffer).Write(0xcef79db5f0, 0xcc4de80000, 0xd, 0x800, 0x0, 0x0, 0x0)
        /usr/local/go/src/bytes/buffer.go:172 +0xdd
fmt.Fprintln(0x14f3400, 0xced2095e30, 0xc006eacd10, 0x1, 0x1, 0x2, 0x2, 0x0)
        /usr/local/go/src/fmt/print.go:265 +0x8b
createI2chart/vendor/github.com/smartystreets/smartystreets-go-sdk/internal/sdk.(*HTTPTraceLogger).WroteHeaders(...)
        /machine/src/createI2chart/vendor/github.com/smartystreets/smartystreets-go-sdk/internal/sdk/tracing_client.go:114
net/http.(*Request).write(0xc350f17300, 0x14f3100, 0xc2f7ca8c40, 0x0, 0xcf04bf8db0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/request.go:655 +0x93c
net/http.(*persistConn).writeLoop(0xcf0f0da5a0)
        /usr/local/go/src/net/http/transport.go:2199 +0x1c8
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1567 +0xb23
```

**Comment by DuncanBeutler** [comment]
Can I see the code that you're running when you get this error? @mzimmerman

**Comment by mzimmerman** [comment]
Apparently, dep ensure -update github.com/smartystreets/smartystreets-go-sdk doesn't actually update the library so I was running a version from ~6 months ago (had the zipcode bug for GET requests only)

I think this was simply a case of being out of memory looking at the stack trace more carefully.  I think this can probably be closed.
